spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.174.128:3306/city?serverTimezone=GMT%2B8&useSSL=false&characterEncoding=utf8&connectTimeout=3000
    username: "root"
    password: "123456"
  #配置redis-cluster集群
  redis:
    cluster:
      nodes: 192.168.174.128:7001,192.168.174.128:7002,192.168.174.128:7003,192.168.174.128:7004,192.168.174.128:7005,192.168.174.128:7006
    jedis:
      pool:
        max-active: 300 #连接池最大连接数
        max-wait: -1 #连接池最大阻塞等待时间(-1表示无限制)
        max-idle: 100 #最大空闲连接数
        min-idle: 20 #最小空闲连接数





mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  typeAliasesPackage: com.jso.entity
  global-config:
    db-config:
      id-type: id_worker
      insert-strategy: not_empty
      update-strategy: not_empty
      select-strategy: not_empty
    banner: false
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    jdbc-type-for-null: null